/**
 * iconset-loader — user-selectable icon sets.
 *
 * A set lives in /ui/iconsets/<id>/ (generated by scripts/kde-icons/convert.py
 * from GPL-3.0 KDE sources) and ships an index.json listing the icon names it
 * provides plus a tint palette for every coloured glyph. The resolver in
 * icon.js tries: active set → theme override → /ui/icons/ (the base set), so a
 * set only needs to carry what it draws differently.
 *
 * Storage is global, like the theme (`ui.theme.name`). The default is
 * 'infinity', whose light/dark variant follows the active theme's mode.
 */

import { themeMode } from './theme-loader.js';

const KEY = 'ui.iconset.name';
const TINT_KEY = 'ui.tint.icons';
const DEFAULT_CHOICE = 'infinity';

/** Choices shown in Settings → Appearance. `auto` picks a dir per theme mode. */
const OPTIONS = [
  {
    value: 'infinity',
    label: 'Infinity (coloured)',
    hint: 'The Infinity icon theme — coloured folders and app icons, auto light/dark.',
    auto: { light: 'infinity', dark: 'infinity-dark' },
  },
  {
    value: 'base',
    label: 'Slot-Beauty (monochrome)',
    hint: 'The KDE Slot-Beauty line-icon set the app was originally built on.',
  },
];

let choice = DEFAULT_CHOICE;
let resolvedDir = null; // directory under /ui/iconsets/, or null for the base set
const indexes = new Map(); // dir -> Promise<index|null>

function optionFor(value) {
  return OPTIONS.find((o) => o.value === value) || OPTIONS[0];
}

function resolve(themeMode) {
  const option = optionFor(choice);
  if (!option.auto) return null;
  return option.auto[themeMode === 'light' ? 'light' : 'dark'] || null;
}

/** Boot: read the stored choice and resolve it against the current theme. */
export function initIconLoader() {
  const stored = localStorage.getItem(KEY);
  choice = OPTIONS.some((o) => o.value === stored) ? stored : DEFAULT_CHOICE;
  resolvedDir = resolve(themeMode());
  // The theme loader owns the mode; re-resolve when the theme changes.
  window.addEventListener('theme:change', () => {
    const next = resolve(themeMode());
    if (next !== resolvedDir) {
      resolvedDir = next;
      window.dispatchEvent(new CustomEvent('iconset:change', { detail: { iconset: choice, dir: resolvedDir } }));
    }
  });
}

export function iconsetOptions() {
  return OPTIONS.map(({ value, label, hint }) => ({ value, label, hint }));
}

export function getIconsetChoice() {
  return choice;
}

/** The active set directory id ('infinity', 'infinity-dark', …) or null. */
export function getActiveIconset() {
  return resolvedDir;
}

/** Switch the set (persists globally, repaints via the iconset:change event). */
export function setIconset(value) {
  if (!OPTIONS.some((o) => o.value === value) || value === choice) return false;
  choice = value;
  localStorage.setItem(KEY, value);
  const next = resolve(themeMode());
  resolvedDir = next;
  window.dispatchEvent(new CustomEvent('iconset:change', { detail: { iconset: choice, dir: resolvedDir } }));
  return true;
}

/** The active set's index.json (names + tint palettes), or null. */
export function loadSetIndex(dir = resolvedDir) {
  if (!dir) return Promise.resolve(null);
  if (!indexes.has(dir)) {
    indexes.set(dir, fetch(`/ui/iconsets/${dir}/index.json`)
      .then((res) => (res.ok ? res.json() : null))
      .catch(() => null));
  }
  return indexes.get(dir);
}

/** Whether the active set ships `name` (the base set answers true). */
export async function setHas(name) {
  if (!resolvedDir) return false;
  const index = await loadSetIndex();
  const names = index?.names || {};
  return Object.values(names).some((list) => list.includes(name));
}

/**
 * The tint palette for `name` in the active set: [[hex, position], …] where
 * position 0 = darkest paint and 1 = lightest. Falls back to the base set's
 * generated palette (e.g. the Slot-Beauty folder) when the set ships none.
 */
export async function paletteFor(name) {
  const index = await loadSetIndex();
  if (index?.tint?.[name]?.length >= 2) return index.tint[name];
  const base = await loadSetIndex('__base__');
  return base?.tint?.[name] || null;
}

/** Base-set index (used for palettes and lookup metadata). */
if (typeof window !== 'undefined') {
  indexes.set('__base__', fetch('/ui/icons/index.json')
    .then((res) => (res.ok ? res.json() : null))
    .catch(() => null));
}

export function tintEnabled() {
  return localStorage.getItem(TINT_KEY) === '1';
}

/** Accent-tint coloured icons on/off (persists globally). */
export function setTint(on) {
  const next = on ? '1' : '0';
  if (localStorage.getItem(TINT_KEY) === next) return;
  localStorage.setItem(TINT_KEY, next);
  window.dispatchEvent(new CustomEvent('tint:change', { detail: { tint: !!on } }));
}
