-- The Browser's download history.
--
-- The shell (`peakd`) performs every download; the window relays each lifecycle
-- event here so the downloads panel survives closing the window or restarting
-- the shell. Rows are best-effort (like `peakd_history`): a broken database
-- must never stall or fail a download.
--
-- Ids are generated by the shell (`d1`, `d2`, …) and stable for the life of a
-- download. `state` is one of: requested, downloading, paused, completed,
-- cancelled, interrupted.

CREATE TABLE IF NOT EXISTS browser_downloads (
    id          TEXT NOT NULL,
    traveler_id TEXT NOT NULL,
    url         TEXT NOT NULL,
    host        TEXT,
    file_name   TEXT,
    file_path   TEXT,
    mime        TEXT,
    total       INTEGER NOT NULL DEFAULT 0,
    received    INTEGER NOT NULL DEFAULT 0,
    state       TEXT NOT NULL DEFAULT 'download',
    error       TEXT,
    incognito   INTEGER NOT NULL DEFAULT 0,
    created_at  TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at  TEXT NOT NULL DEFAULT (datetime('now')),
    PRIMARY KEY (traveler_id, id)
);

-- The panel lists a user's downloads newest-first.
CREATE INDEX IF NOT EXISTS idx_browser_downloads_traveler_created
    ON browser_downloads (traveler_id, created_at DESC);
